name: Increment Version for Dev

on:
  push:
    branches:
      - dev

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Increment patch version
        run: node increment-version.js patch

      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Incremented patch version to $(cat package.json | jq -r .version)"
          git push
