name: Increment Version

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install || { echo "Error: npm install failed"; exit 1; }
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Debug - Show branch information
        run: |
          echo "Branch: ${{ github.ref }}"

      - name: Determine the branch and increment type
        id: increment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "type=minor" >> $GITHUB_ENV
            echo "Increment type set to minor."
          else
            echo "type=patch" >> $GITHUB_ENV
            echo "Increment type set to patch."
          fi

      - name: Debug - Show increment type
        run: echo "Increment type is ${{ env.type }}"

      - name: Increment version
        run: |
          node increment-version.js ${{ env.type }} || { echo "Error: increment-version.js failed"; exit 1; }

      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Incremented ${{ env.type }} version to $(cat package.json | jq -r .version)" || echo "No changes to commit"

      - name: Push changes to both main and dev branches
        run: |
          git push origin ${{ github.ref }} || { echo "Error: Push to ${{ github.ref }} failed"; exit 1; }
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            git push origin main:dev || { echo "Error: Push to dev branch failed"; exit 1; }
          fi
